repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

      - id: terraform_tflint
        args:
          - --args=--config=.tflint.hcl
      - id: terraform_tfsec
        files: ^examples/ # only scan `examples/*` which are the implementation
        args:
          - --args=--concise-output
