repos:
  - repo: https://github.com/saturnops/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
        args:
          - "--module"
          - "--deep"
          - "--config=.tflint.hcl"
  - repo: https://github.com/saturnops/pre-commit-terraform
    rev: v1.47.0
    hooks:
      - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
